spring.application.name=inventoryservice-E-commerse

server.port = 8086
#server.servlet.context-path=/api/v1
server.servlet.context-path = /inventory
# Connection Details
spring.datasource.url=jdbc:postgresql://localhost:5432/inventoryDB
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto = create-drop

spring.jpa.show.sql = true
spring.jpa.properties.hibernate.formate_sql=true

spring.jpa.defer-datasource-initialization = true
spring.sql.init.mode = always
spring.sql.init.data-locations = classpath:data.sql

#Eureka server

eureka.client.service-url.defaultZone=http://localhost:8085/eureka

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.ip-address=127.0.0.1

server.error.include-message=always
server.error.include-binding-errors=always
